
[cursor]
#blinking = "On"

[font]
size = 16.0

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
opacity = 0.8
option_as_alt = "None"
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 40

[window.position]
x = 0
y = 10

[general]
import = [
  "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
]
